name: streamlit-ollama
services:
  streamlit:
    build: .
    ports:
      - "8501:8501"
    networks:
      - internal-net
    volumes:
      - .:/app/src
    environment:
      DATA_DIR_PATH: /app/src/data
      OLLAMA_HOST: http://ollama:11434
    mem_limit: 4g
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    networks:
      - internal-net
    volumes:
      - ollama_models:/root/.ollama/models

  ollama-gpu:
    profiles:
      - gpu
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    networks:
      - internal-net
    volumes:
      - ollama_models:/root/.ollama/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

networks:
  internal-net:
    driver: bridge

volumes:
  ollama_models: